/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Myc1: typeof import('./components/myc1.vue')['default']
    Myc2Age: typeof import('./components/myc2-age.vue')['default']
    Myc3Movie: typeof import('./components/myc3-movie.vue')['default']
    MycCounter: typeof import('./components/myc-counter.vue')['default']
    PiniaCartView: typeof import('./components/PiniaCartView.vue')['default']
    PiniaExample: typeof import('./components/PiniaExample.vue')['default']
    PiniaExampleMerch: typeof import('./components/PiniaExampleMerch.vue')['default']
    PiniaHomeView: typeof import('./components/PiniaHomeView.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelfComponent: typeof import('./components/SelfComponent.vue')['default']
    TheCounter: typeof import('./components/TheCounter.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheInput: typeof import('./components/TheInput.vue')['default']
  }
}
